; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Remove optimization to start
build_unflags = -Os   ; Default platformIO optimization is for small size
  
; Set breakpoint mode
build_flags =
  -DAVR8_BREAKPOINT_MODE=1
  -O0   ; turns off all optimizations, which is best for debugging.  Code will generally run as you typed it.

debug_tool=avr-stub
debug_port=/dev/ttyACM0
; GDB stub implementation
lib_deps =
    jdolinay/avr-debugger ;@ ~1.4